trigger:
- main

# 关键配置：全局限制并行度为1
pool:
  vmImage: ubuntu-latest
  parallelism: 1  # 强制整个流水线单线程执行

jobs:
- job: Build_and_Test
  steps:
  - script: echo "构建与测试..."
  
- job: Deploy_Dev
  dependsOn: Build_and_Test
  steps:
  - script: echo "部署到开发环境..."

- job: Deploy_Prod
  dependsOn: Deploy_Dev
  steps:
  - script: echo "部署到生产环境..."
